# Databricks notebook source
# MAGIC %md
# MAGIC # U1 — Action Plane setup (Lakebase DDL + seed policies)
# MAGIC
# MAGIC *The "agents that act" expansion — the single governed plane every agent acts through.*
# MAGIC
# MAGIC This notebook stands up the three Lakebase tables behind the **Action Plane** and seeds the
# MAGIC guardrail policies. It is the schema half of unit **U1**; the reusable Python module lives in
# MAGIC `apps/_shared/action_plane/` (`model.py` = state machine, `guardrails.py` = policy engine).
# MAGIC
# MAGIC | Table | What it holds |
# MAGIC |---|---|
# MAGIC | `actions` | the canonical action record + its state-machine status |
# MAGIC | `action_events` | append-only audit + lineage — one row per transition |
# MAGIC | `action_policies` | the guardrail rules, keyed by `action_type` |
# MAGIC
# MAGIC **State machine** (enforced in `model.py`): `proposed → approved → executing → executed`, with
# MAGIC `rejected` / `failed` terminal branches and `escalated` reachable from any live state on a
# MAGIC guardrail breach. The DDL is idempotent (`CREATE TABLE IF NOT EXISTS`) so re-running is safe.
# MAGIC
# MAGIC ### Write governance — the honest story
# MAGIC OBO + UC/RLS govern **reads**. These **writes/executions** are governed by a separate plane:
# MAGIC **app/service identity + policy guardrails + approval gate + full audit/lineage**. `actions` is
# MAGIC the canonical record; `action_events` is the lineage; `action_policies` is the guardrail contract.

# COMMAND ----------

# MAGIC %md
# MAGIC ## Setup — connect to Lakebase `graphrag-spike`, schema `akzo`
# MAGIC
# MAGIC | Field | Value |
# MAGIC |---|---|
# MAGIC | host | the instance `read_write_dns` |
# MAGIC | port | `5432` |
# MAGIC | dbname | `databricks_postgres` |
# MAGIC | user | your email — the OAuth principal / write identity |
# MAGIC | password | a short-lived DB credential token (SDK-generated, ~1h) |
# MAGIC | sslmode | `require` |
# MAGIC
# MAGIC psycopg (psycopg3) is preinstalled on serverless.

# COMMAND ----------

from contextlib import contextmanager

import psycopg
from databricks.sdk import WorkspaceClient

INSTANCE_NAME = "graphrag-spike"
DB_NAME = "databricks_postgres"
PG_SCHEMA = "akzo"

w = WorkspaceClient()
inst = w.database.get_database_instance(name=INSTANCE_NAME)
PG_HOST = inst.read_write_dns
PG_USER = w.current_user.me().user_name

print("Lakebase instance :", INSTANCE_NAME, "(", inst.state, ")")
print("Host (read_write) :", PG_HOST)
print("Database / schema :", DB_NAME, "/", PG_SCHEMA)
print("Write identity    :", PG_USER)


def _db_token() -> str:
    """Short-lived Lakebase credential — the app/service write identity."""
    return w.database.generate_database_credential(instance_names=[INSTANCE_NAME]).token


@contextmanager
def pg():
    conn = psycopg.connect(
        host=PG_HOST, port=5432, dbname=DB_NAME,
        user=PG_USER, password=_db_token(), sslmode="require", autocommit=True,
    )
    try:
        with conn.cursor() as cur:
            cur.execute(f"SET search_path TO {PG_SCHEMA}")
        yield conn
    finally:
        conn.close()


with pg() as conn, conn.cursor() as cur:
    cur.execute("SELECT current_user, current_database()")
    print("Connected as:", cur.fetchone())

# COMMAND ----------

# MAGIC %md
# MAGIC ## DDL — `actions`, `action_events`, `action_policies`
# MAGIC
# MAGIC `actions(id serial pk, agent, action_type, subject, payload jsonb, status, level, region,
# MAGIC requested_by, approved_by, created_at, decided_at, executed_at, result jsonb, external_ref)`;
# MAGIC `action_events(id, action_id fk, ts, event, actor, detail)`;
# MAGIC `action_policies(action_type pk, max_discount_pct, max_spend_eur, allowed_regions text[],
# MAGIC requires_approval bool)`. All idempotent.

# COMMAND ----------

DDL = [
    f"CREATE SCHEMA IF NOT EXISTS {PG_SCHEMA}",
    """CREATE TABLE IF NOT EXISTS actions (
        id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        agent         TEXT NOT NULL,
        action_type   TEXT NOT NULL,
        subject       TEXT NOT NULL,
        payload       JSONB NOT NULL DEFAULT '{}'::jsonb,
        status        TEXT NOT NULL DEFAULT 'proposed',
        level         INTEGER NOT NULL DEFAULT 2,
        region        TEXT,
        requested_by  TEXT NOT NULL,
        approved_by   TEXT,
        created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
        decided_at    TIMESTAMPTZ,
        executed_at   TIMESTAMPTZ,
        result        JSONB,
        external_ref  TEXT)""",
    """CREATE TABLE IF NOT EXISTS action_events (
        id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        action_id  BIGINT NOT NULL REFERENCES actions(id),
        ts         TIMESTAMPTZ NOT NULL DEFAULT now(),
        event      TEXT NOT NULL,
        actor      TEXT NOT NULL,
        detail     JSONB)""",
    """CREATE TABLE IF NOT EXISTS action_policies (
        action_type       TEXT PRIMARY KEY,
        max_discount_pct  NUMERIC(5,2),
        max_spend_eur     NUMERIC(14,2),
        allowed_regions   TEXT[],
        requires_approval BOOLEAN NOT NULL DEFAULT TRUE)""",
    "CREATE INDEX IF NOT EXISTS idx_actions_status ON actions(status)",
    "CREATE INDEX IF NOT EXISTS idx_actions_agent ON actions(agent)",
    "CREATE INDEX IF NOT EXISTS idx_action_events_action ON action_events(action_id)",
]

with pg() as conn, conn.cursor() as cur:
    for stmt in DDL:
        cur.execute(stmt)
print("DDL applied — actions / action_events / action_policies ready.")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Seed realistic guardrail policies
# MAGIC
# MAGIC One row per action type the agents can take. Caps are deliberately realistic for the AkzoNobel
# MAGIC Paints/Coatings story so the demo shows both an in-policy execute and a breach→escalate.
# MAGIC `ON CONFLICT` makes the seed idempotent and re-tunable.

# COMMAND ----------

EMEA = ["EMEA", "NL", "DE", "FR", "UK", "BE", "ES", "IT"]

POLICIES = [
    # action_type,        max_discount_pct, max_spend_eur, allowed_regions, requires_approval
    ("quote_send",        15.0,   250000.0,  EMEA,                       True),
    ("price_change",      10.0,   None,      EMEA,                       True),
    ("forecast_override", None,   None,      EMEA,                       True),
    ("scm_reorder",       None,   100000.0,  EMEA,                       True),
    ("scm_reroute",       None,   50000.0,   EMEA,                       True),
    ("crm_task",          None,   None,      EMEA,                       False),
    ("escalation",        None,   None,      None,                       False),
]

UPSERT = """
    INSERT INTO action_policies
        (action_type, max_discount_pct, max_spend_eur, allowed_regions, requires_approval)
    VALUES (%s, %s, %s, %s, %s)
    ON CONFLICT (action_type) DO UPDATE SET
        max_discount_pct  = EXCLUDED.max_discount_pct,
        max_spend_eur     = EXCLUDED.max_spend_eur,
        allowed_regions   = EXCLUDED.allowed_regions,
        requires_approval = EXCLUDED.requires_approval
"""

with pg() as conn, conn.cursor() as cur:
    for p in POLICIES:
        cur.execute(UPSERT, p)
    cur.execute("SELECT action_type, max_discount_pct, max_spend_eur, "
                "allowed_regions, requires_approval FROM action_policies ORDER BY action_type")
    for row in cur.fetchall():
        print(row)

print("Seeded", len(POLICIES), "policies.")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Verify — schema + row counts
# MAGIC
# MAGIC The action plane is now live. From here, `apps/_shared/action_plane` (`ActionPlane`, `evaluate`)
# MAGIC drives the state machine and guardrails — U3 (executor), U6 (Action Center), U7 (the three apps)
# MAGIC all consume this same plane.

# COMMAND ----------

with pg() as conn, conn.cursor() as cur:
    for tbl in ("actions", "action_events", "action_policies"):
        cur.execute(f"SELECT count(*) FROM {tbl}")
        print(f"{tbl:18s} rows = {cur.fetchone()[0]}")
